### ISSUE TITLE
AX Exchange error: Error Domain=Accessibility Code=0

### ISSUE THREAD

**Issue by khandpur** [google/EarlGrey#331] opened 2016-11-02 21:43 UTC
For apps that use MFMailComposerViewController or SFSafariViewController, we're seeing a spam of error messages:
AX Exchange error: Error Domain=Accessibility Code=0 "Remote service does not respond to _accessibilityMachPort" UserInfo={NSLocalizedDescription=Remote service does not respond to _accessibilityMachPort}

and it blocks testing as the test case just hangs.

**Comment by tirodkar** [comment] 2016-11-02 21:44
Closing as this is a duplicate of https://github.com/google/EarlGrey/issues/108

**Closed by tirodkar** 2016-11-02 21:44 UTC
Labels: P1
