### ISSUE TITLE
EarlGrey runs slower compared to KIF/XCUITEST

### ISSUE THREAD

**Issue by yaphatak** [google/EarlGrey#471] opened 2017-03-27 19:13 UTC
`Mac OS : 10.11.6
iOS : 10.2
EarlGrey: 1.6`

If I change setting to `(GREYConfiguration.sharedInstance() as AnyObject).setValue(false, forConfigKey: kGREYConfigKeySynchronizationEnabled)`, Its much faster

**Comment by khandpur** [comment] 2017-04-01 03:05
@yaphatak  What scenarios?

**Comment by yaphatak** [comment] 2017-04-03 23:15
I just created for @tirodkar . Issue is actually raised by ahmedeid from Slack.

**Comment by tirodkar** [comment] 2017-04-06 21:59
++ https://github.com/AhmedEid

**Comment by sskhandp** [comment] 2017-04-19 19:49
I don't have Ahmed's github id so unable to tag him on here...

@tirodkar Could you please find out which scenarios and/or actions this is referring to?

**Comment by tirodkar** [comment] 2017-04-19 20:15
Actually, I'm closing this now. The issue is visible with XCUITest / running a regular app as well on my machine and seems to be independent to EarlGrey.

The test in question was slow because of the order of matchers being passed in. grey_sufficientlyVisible() was the first matcher in grey_allOf(), IIRC.

**Closed by tirodkar** 2017-04-19 20:15 UTC
