### ISSUE TITLE
Getting a EXC_BAD_ACCESS on GREYAppStateTracker.m

### ISSUE THREAD

**Issue by tapthaker** [google/EarlGrey#81] opened 2016-05-10 11:01 UTC
Not sure what else info I can put forward so that you can debug the issue. I am using Carthage as Dependency Manager and pointing to master.

![screen shot 2016-05-10 at 4 27 54 pm](https://cloud.githubusercontent.com/assets/7520741/15144362/92c9ac4a-16cc-11e6-96a8-76f6a062684e.png)

**Comment by khandpur** [comment] 2016-05-11 05:57
Thanks for reporting this Tapan. Is there anyway you can share the project that we can use for reproducing this? We encountered this internally while testing the framework but were unable to reproduce it after several days of trying.

**Comment by tapthaker** [comment] 2016-05-11 05:59
Can't share the project with you. Will try to reproduce with a sample and get back to you.

**Comment by khandpur** [comment] 2016-05-24 21:15
Hey Tapan, were you able to repro this?

**Comment by tapthaker** [comment] 2016-05-25 04:40
I will attach a demo project to this issue today or tomorrow.

**Comment by khandpur** [comment] 2016-06-01 06:12
hey Tapan, any updates?

**Comment by tapthaker** [comment] 2016-06-06 18:59
Hey Sundeep,
Sorry for the delay, I tried really hard to recreate in the demo project but I am unable to. Not sure why i am getting a EXEC_BAD_ACCESS 

The following might help:
Getting the same exception if I try to print the description of [NSThread callStackSymbols] before setting it inside _elementIDToCallStack.

**Comment by khandpur** [comment] 2016-06-07 06:29
Like this:
```
       NSLog(@"%@", [NSThread callStackSymbols]);
        // TODO: Consider tracking callStackSymbols for all states, not just the last one.
        [_elementIDToCallStack setObject:[NSThread callStackSymbols] forKey:internalElementID];
```
?

the NSLog above worked fine for me.

**Comment by tapthaker** [comment] 2016-06-07 07:09
Yes. While trying this I found something interesting. After taking the latest pull the issue seems fixed. I will figure out the exact commit and let you know.

**Comment by khandpur** [comment] 2016-08-08 06:49
Closing this. Feel free to open if this issue resurfaces.

**Closed by khandpur** 2016-08-08 06:49 UTC
