### ISSUE TITLE
Travis is failing

### ISSUE THREAD

**Issue by bootstraponline** [google/EarlGrey#50] opened 2016-03-21 03:12 UTC
I updated [the docs](https://github.com/google/EarlGrey/pull/49) and was surprised to see [all the Travis failures.](https://travis-ci.org/google/EarlGrey/builds/116943764)
## 

> The job exceeded the maxmimum time limit for jobs, and has been terminated.
> 
> https://travis-ci.org/google/EarlGrey/jobs/116943768
## 

> Executed 208 tests, with 2 failures (2 unexpected) in 2361.286 (2361.643) seconds
> 
> https://travis-ci.org/google/EarlGrey/jobs/116943769

**Comment by tirodkar** [comment] 2016-03-21 23:05
Thanks for bringing this to our attention @bootstraponline, we're currently working on fixing these issues.

**Comment by bootstraponline** [comment] 2016-04-06 00:45
Travis has a [hard limit of 50 minutes for Mac builds.](https://docs.travis-ci.com/user/customizing-the-build/#Build-Timeouts) If there was some way to cache the app build instead of recompiling every time, that might help.

For appium, we've had to use an open source cloudbees account with [on premise executors](https://documentation.cloudbees.com/docs/dev-at-cloud/On-Premise+Executors.html) (via AWS) because Travis doesn't play nice with lots of UI tests.

**Comment by khandpur** [comment] 2016-04-06 00:58
Yeah it's been pretty annoying trying to work around that. Also, Travis has a log size limit of 2 (or 3) mb I don't quite recall exactly. I switched to using xcpretty for that reason however I think xcpretty sometimes hangs or at least doesn't output stuff which makes travis believe xcodebuild is stuck for more than 10 mins and it terminates our test run.

**Comment by bootstraponline** [comment] 2016-04-06 01:06
Yeah, another awesome feature of Travis:

> If no output is received from a build for 10 minutes, it’s assumed to have stalled for unknown reasons and is subsequently killed.
> https://docs.travis-ci.com/user/common-build-problems/

Probably why [Swift provides their own hardware for CI](https://swift.org/blog/swift-ci/). Hopefully Google has some way of provisioning Macs for builds. I wish there was an AWS like service for Mac builds (without silly timeouts).

**Comment by bootstraponline** [comment] 2016-04-06 18:17
[Travis uses MacStadium](http://www.macstadium.com/blog/how-travis-ci-halved-boot-times-for-os-x-and-ios-testing-at-macstadium/). Using them directly would mean no limits on the builds. For CI, it'd be easy to plug into a free cloudbees jenkins account.

**Comment by tirodkar** [comment] 2017-01-13 03:29
Does this still need to be open?

**Comment by bootstraponline** [comment] 2017-01-13 03:55
Yes, Travis is still failing. 

https://travis-ci.org/google/EarlGrey

**Comment by khandpur** [comment] 2017-08-29 01:12
Duplicate of https://github.com/google/EarlGrey/issues/181

**Closed by khandpur** 2017-08-29 01:12 UTC
Labels: P1, type: bug
