### ISSUE TITLE
FTRKeyboardKeysTest fails on iPad - iOS 10

### ISSUE THREAD

**Issue by mbaxley** [google/EarlGrey#239] opened 2016-08-26 22:30 UTC
Multiple typing tests fail when run on iOS 10 iPad Air 2. I tested on beta 5 and beta 6. All the tests passed when I ran it on iPhone 6s simulator on iOS 10 beta 6.

testSymbolsTyping failed 5 out of 5 times (for a simple test case to repro).

Some of the other tests that failed on iOS 10 iPad were:
testNumbersAndSpacesTyping
testSymbolsAndSpacesTyping
testUIKeyboardTypeASCIICapable
testUIKeyboardTypeWebSearch

**Comment by tirodkar** [comment] 2016-08-26 22:32
Thanks for bringing this to our attention @mbaxley, we'll test it out asap.

**Comment by mbaxley** [comment] 2016-08-31 18:09
Thanks! I have one semi-related question. In other frameworks, we typically avoided the delay of typing (and flake that wasn't un-common) by having utilities to paste text. Is this something EarlGrey plans to support (or supports and I didn't find it)? Or do you prefer clients do this type of thing themselves?

**Comment by bootstraponline** [comment] 2016-08-31 18:13
I added support for replace text which bypasses typing. That should do what you want.

**Comment by liaoyuke** [comment] 2016-09-17 00:35
I debugged this issue, and find out that it is caused by bad synchronization.

The implementation of EarlGrey's tapKey function is as following:

> [gTapKeyAction perform:key error:nil];
> [[[GREYKeyboard grey_keyboardObject] taskQueue] waitUntilAllTasksAreFinished];
> [[GREYUIThreadExecutor sharedInstance] drainOnce];

When typing a string, it basically types a character and wait for **some amount of time** (drainOnce) before typing next one. The tests fail because the animation, triggered by switching keyboard mode, is taking longer to finish than the waiting time, so it happens that EarlGrey tries to look for a key and couldn't find it, but actually the key will appear later.

A simple fix to the bug is to wait until UI finishes:
"[[GREYUIThreadExecutor sharedInstance] drainOnce]" => "[[GREYUIThreadExecutor sharedInstance] drainUntilIdle]"
But this simple fix would also slows down the typing speed.

I'm not sure why this is happening only on iPad on iOS 10, maybe it's because Apple changed the way switching keyboard mode works, or maybe not... I'll follow up if I find more information.

**Comment by tirodkar** [comment] 2016-09-17 00:37
@liaoyuke, what you're saying is precisely what I'm trying to do [here](https://github.com/google/EarlGrey/pull/272/files#diff-645ec08a66bbdc2ebc9af618844a9865R465). Thought it does cause quite some failures. I wonder how many users would be fine with slow typing?

**Comment by bootstraponline** [comment] 2016-09-17 01:49
Slow & stable is better than fast + flaky. For fast typing, replace text is a better choice.

**Comment by mbaxley** [comment] 2016-09-26 18:29
Flaky typing is definitely way worse than slow typing. My only concern about slowing it down is making sure that draining until idle actually fixes the problem, and isn't acting as a delay which doesn't address the underlying issue. If It is logical why drainUntilIdle fixes it, then I think it's fine.

**Comment by tirodkar** [comment] 2016-09-26 19:23
@mbaxley, that's precisely what adding drain until idle did to the travis tests in my test PR. It seems that we need to focus more on synchronizing correctly with the keyboard rather than change the delay amount.

**Comment by liaoyuke** [comment] 2016-09-26 21:24
I wonder if it is redundant to have waitUntilAllTasksAreFinished? Since drainUntilIdle is going to wait for the UI to finish loading anyway.

**Comment by ArielSD** [comment] 2017-02-06 16:04
I'm still seeing these errors with drainUntilIdle.

**Comment by ynzhang0509** [comment] 2018-04-04 18:55
This issue should be fixed in https://github.com/google/EarlGrey/commit/499474e02cc486b65c360da362173ec77e7495ee.

**Closed** 2018-04-04 19:04 UTC
Labels: type: bug
